In [2]:
import numpy as np

# first , create array with 10 zeros
ten_zeros = np.zeros(10)
print(ten_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# second create table with 10 ones
ten_ones = np.ones(10)
print(ten_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
# third create array with 10 fives
ten_ones = np.ones(10)
ten_fives = ten_ones * 5
print(ten_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [10]:
# forth , create array of intengers from 10-to 50
array_10_50 = np.arange(10, 51)
print(array_10_50)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [12]:
# fifth, create array with all the even numbers 10-50
array_10_50_even = np.arange(10, 51, 2)
print(array_10_50_even)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [18]:
# sixth , create a 3X3 matrix with values ranging from 0 to 8.
array_three_three = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(array_three_three)
print(array_three_three.shape)  # confirm that is 3x3 array.


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)


In [23]:
# seventh , create a 3X3 identity matrix
identity_array = np.eye(3)  # or np.identity(3)
print(identity_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [44]:
# eighth , create a random number from 0-1 
random_number = np.random.rand()
print(random_number)




0.909160429387082


In [50]:
# ninenth , create array with 25 random numbers
random_array = np.random.randn(5, 5)
print(random_array)


[[-0.59121569  1.29650437  0.8528566   1.65163751 -0.00887171]
 [ 0.96926258  1.05148965  0.30321807 -2.43772282  1.08401198]
 [ 0.26745345 -0.13932251 -0.18471791  0.95095483 -1.30219023]
 [ 0.73073147 -0.70748765  0.44976874 -0.81308133 -0.73875606]
 [ 0.97456992  0.87646327  0.38143098  0.38070966  0.59841194]]


In [55]:
# tennth , create the following array which is given (udemy page)
matrix = np.arange(0.01, 1.01, 0.01)
# print(matrix)
reshape_array = matrix.reshape(10, 10)
print(reshape_array)
print(reshape_array.shape)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]
(10, 10)


In [57]:
# eleventh , create array of 20 linearly spaced points between 0-1
linearly_matrix = np.linspace(0, 1, 20)
print(linearly_matrix)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [78]:
# exercises with indexing and selection
# first , you will be given a few matrices and be asked to replicate the resulting matrix outputs.
mat = np.arange(1, 26).reshape(5, 5)
print(mat)
print()
indexing_mat = mat[2:, 1:]  # it is asked to print the numbers 12,13,14,15,17,18,19,20,22,23,24,25.
print(indexing_mat)
print()
print(mat[3, 4])  # it is asked to print the 20.
print()
print(mat[3:, :])  # it is asked to print the numbers 16 , 17,18,19,20,21,22,23,24,25
print()
# get all the sum in the mat array
print(mat.sum())

# get the standard deviation of the values in matrix mat
print(mat.std())
print()

# get the sum of all the columns in mat
print(mat.sum(axis=0))  # axis=0 is for columns and axis=1 for rows!!!

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]

20

[[16 17 18 19 20]
 [21 22 23 24 25]]

325
7.211102550927978

[55 60 65 70 75]
